[platformio]
default_envs = transmitter

; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  madhephaestus/ESP32Servo

build_flags =
  -I include

; -------- Build Transmitter --------
[env:transmitter]
build_src_filter =
  +<transmitter.cpp>
  -<receiver.cpp>

; -------- Build Receiver --------
[env:receiver]
build_src_filter =
  +<receiver.cpp>
  -<transmitter.cpp>