; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
  

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  madhephaestus/ESP32Servo

build_flags =
  -I include

  ; -------- Build Pulse Check --------
[env:Pulse]
build_src_filter =
  +<Phase_1_Pulse_Check.cpp>

; -------- Build Single Board System --------
[env:RPM]
build_src_filter =
  +<RPM_Check.cpp>

[env:Dual_RPM]
build_src_filter =
  +<Dual_RPM_Sensor.cpp>

[env:Auto_RPM]
build_src_filter =
  +<RPM_Throttle.cpp>

[env:Phase_1]
build_src_filter =
  +<Phase_1_Pulse_Check.cpp>

[env:Phase_2]
build_src_filter =
  +<Phase_2_Pulse_Detection.cpp>

[env:Phase_3]
build_src_filter =
  +<Phase_3_Measuing_Pulse_Periods.cpp>

[env:Phase_4]
build_src_filter =
  +<Phase_4_RPM_Calc.cpp>

[env:Phase_4_5]
build_src_filter =
  +<Phase_4.5_Teleplot_RPM.cpp>

[env:Phase_6a]
build_src_filter =
  +<Phase_6a_Interpt.cpp>

[env:Phase_7]
build_src_filter =
  +<Phase_7_FastPulse_Rejection.cpp>

[env:Phase_8]
build_src_filter =
  +<Phase_8_Outlier_Rejection.cpp>

[env:Phase_9]
build_src_filter =
  +<Phase_9_RPM_Filter.cpp>

[env:Phase_10]
build_src_filter =
  +<Phase_10_RPM_OLED.cpp>

[env:PID_Control]
build_src_filter =
  +<PID_BLDC_Controller.cpp>
 