[platformio]
default_envs = main
; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  

build_flags =
  -I include


[env:main]
build_src_filter =
  +<main.cpp>
  -<alternatecode.cpp>


[env:alternate-code]
build_src_filter =
  +<alternatecode.cpp>
  -<main.cpp>
