; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  madhephaestus/ESP32Servo
  fastled/FastLED@3.9.15


build_flags =
  -I include

[env:Step_1_Manual_Servo_Control]
build_src_filter =
  +<manual_servo.cpp>

[env:Step_4]
build_src_filter =
  +<step4_Servo_Limit.cpp>