[platformio]
default_envs = sensor-test

; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24

build_flags =
  -I include


[env:i2c-reader]
build_src_filter =
  +<main.cpp>
  -<sensor_reader.cpp>
  -<Static and Venturi.cpp>


[env:sensor-test]
build_src_filter =
  +<sensor_reader.cpp>
  -<main.cpp>
  -<Static and Venturi.cpp>


[env:Fan_Experiment]
build_src_filter =
  -<sensor_reader.cpp>
  -<main.cpp>
  +<Static and Venturi.cpp>



