; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  madhephaestus/ESP32Servo
  fastled/FastLED@3.9.15


build_flags =
  -I include

[env:Dummy_transmitter]
build_src_filter =
  +<dummy_transmitter.cpp>

[env:Dummy_reciever]
build_src_filter =
  +<dummy_reciever.cpp>

[env:Transmitter]
build_src_filter =
  +<Transmitter_Mark_1.cpp>


[env:Reciever]
build_src_filter =
  +<Reciever_Mark_1.cpp>