; -------- Shared config --------
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  madhephaestus/ESP32Servo
  nrf24/RF24
  madhephaestus/ESP32Servo
  fastled/FastLED@3.9.15


build_flags =
  -I include


[env:Transmitter]
build_src_filter =
  +<Transmitter.cpp>

[env:Dummy_Controller]
build_src_filter =
  +<dummy_reciever.cpp>